# 베이스 이미지로 OpenJDK 7 사용
FROM openjdk:7-jdk-alpine as build

# 필요한 패키지 설치
RUN apk update && apk add --no-cache curl tar bash

# Maven 압축 파일 복사 및 설치
COPY apache-maven-3.8.1-bin.tar.gz /tmp/

RUN mkdir -p /usr/share/maven \
    && tar -zxvf /tmp/apache-maven-3.8.1-bin.tar.gz -C /usr/share/maven --strip-components=1 \
    && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn \
    && rm -f /tmp/apache-maven-3.8.1-bin.tar.gz \
    && rm -rf /var/cache/apk/* /tmp/*

# 환경 변수 설정
ENV MAVEN_HOME=/usr/share/maven \
    MAVEN_CONFIG=/root/.m2 \
    PATH=$MAVEN_HOME/bin:$PATH \
    JAVA_HOME=/usr/lib/jvm/java-1.7-openjdk

# 작업 디렉토리 설정
WORKDIR /usr/src/app

# 소스 파일 복사
COPY . /usr/src/app

# Maven 빌드 실행
CMD ["mvn", "clean", "install"]

